### ISSUE TITLE
Block crashes after selecting audio file(s)

### ISSUE THREAD

**Issue by helen** [10up/retro-winamp-block#30]
**Describe the bug**
After inserting the block and picking one or more audio files, I get the dreaded "this block has encountered an error" message and `TypeError: l.__experimentalUseInnerBlocksProps is not a function` in my console. I have a feeling this is related to my particular install, specifically that I am on WP nightly and perhaps because I have Gutenberg active.

**Steps to Reproduce**

1. Insert Winamp block
2. Choose one or more items from the media library
3. See errors

**Expected behavior**
A working block :)

**Screenshots**

**Environment information**
 - Device: Mac Mini
 - OS: MacOS 11.6
 - Browser and version: Firefox 95.0b4
 - WordPress version: Nightly (currently 5.9-alpha-52211)
 
 - Plugins and version: Gutenberg 11.9.1
 - Theme and version: Tove (FSE)
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by fabiankaegy** [comment]
Yes that is exactly it. 11.9 & 5.9 have stabilized the API for useInnerBlocksProps
