### ISSUE TITLE
page loading at the bottom

### ISSUE THREAD

**Issue by npy88** [10up/retro-winamp-block#38]
### Describe your question

hi thanks so much for this plugin! I'm coming across an issue of my page loading at the bottom (where the player is located) but I need the page to load at the top. Do you know what I could do to fix this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@npy88 can you share an example of this?  Possibly check to see if there are any console errors?  Would also help to confirm your WP version, theme version, Winamp plugin version, and any other active plugin versions in case there's a compatibility issue we need to take into concern.

**Comment by npy88** [comment]
should be viewable here https://www.wifinails.com/test-home/
I have the latest Wordpress version, Winamp version 1.0.1, and the following active plugins:
Elementor 3.5.6
Elementor pro 3.6.3
essential add ons for elementor 5.0.10
image hover effects elementor Addon 1.3.5
insert headers and footers 1.6.0
jetpack 10.7
payment plugins for stripe WooCommerce 3.3.16
shopengine 2.1.0
ultimate add ons for Gutenberg 1.25.4
updraftplus 1.22.8
w3 total cache 2.2.1
WooCommerce 6.2.1
woo commerce paypal payments 1.7.0
wp content copy protection 3.4.5

thank you!

**Comment by iansvo** [comment]
@npy88 Thanks for the additional details on this. I was looking into the issue and I think I have a patch that may do the trick. To be sure, I was hoping you could test this out on your site so we can determine if this fix will be appropriate. In my local testing, it does appear to resolve the issue though.

**Branch link:** https://github.com/10up/retro-winamp-block/tree/fix/issue-38-page-jump-on-load

[retro-winamp-block.zip](https://github.com/10up/retro-winamp-block/files/8655155/retro-winamp-block.zip)

Please install this version of the plugin then let me know if you're still experiencing the issue. This shouldn't cause any data loss or cause your block to need to be set up again. 

If you have any other questions just reply back here.

**Comment by jeffpaul** [comment]
@npy88 any updates from testing @iansvo's branch and whether that resolves your issue?

**Comment by jeffpaul** [comment]
@iansvo might as well be worth opening as a PR for us to get through code review in case this does resolve things for @npy88.

**Comment by npy88** [comment]
I’m so sorry im just now seeing these messages  I will try to test and check in with you guys this week. thanks so much!

**Comment by iansvo** [comment]
PR has been added: https://github.com/10up/retro-winamp-block/pull/56
