### ISSUE TITLE
add support for Milkdrop visualizations

### ISSUE THREAD

**Issue by jeffpaul** [10up/retro-winamp-block#45]
### Is your enhancement related to a problem? Please describe.

As noted by Justin Tadlock here: https://wptavern.com/a-throwback-to-the-past-retro-winamp-block?utm_source=rss&utm_medium=rss&utm_campaign=a-throwback-to-the-past-retro-winamp-block
> If I had one wish for this plugin, it would be to see the addition of Milkdrop, the popular Winamp visualizer add-on.

We'll need to assess if this is available in Webamp and how that might render on mobile layouts, plus how you might change the various visualizations available (and whether that might be another block setting or not).

### Designs

![image](https://user-images.githubusercontent.com/2818133/164038855-2b1428bd-8e13-4c32-8647-7c27c0e98352.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gsarig** [comment]
This is available on webamp and can be enabled by adding the following to `frontend.js`:
```
options.__butterchurnOptions = {
importButterchurn: () => {
	// Only load butterchurn when music starts playing to reduce initial page load
	return import('butterchurn');
},
getPresets: () => {
	const presets = butterchurnPresets.getPresets();
	return Object.keys(presets).map((name) => {
		return {
			name,
			butterchurnPresetObject: presets[name]
		};
	});
},
butterchurnOpen: true
};
options.__initialWindowLayout = {
    main: { position: { x: 0, y: 0 } },
    equalizer: { position: { x: 0, y: 116 } },
    playlist: { position: { x: 0, y: 232 }, size: [0, 4] },
    milkdrop: { position: { x: 275, y: 0 }, size: [7, 12] }
}
```
It will produce the following on the desktop: 
![image](https://user-images.githubusercontent.com/5892287/193641402-330cc54d-7bfb-44c1-a764-9140954f71a3.png)

On mobile, though, while the Milkdrop window sits nicely at the bottom of the window, there is an overflow and issue:
![image](https://user-images.githubusercontent.com/5892287/193641800-36ea3e71-5930-457e-9f9a-746eef9c4ac1.png)

Omitting the `options.__initialWindowLayout` values fixes mobile, but then, desktop doesn't look too good, as it's identical to mobile.  This could potentially be addressed if we add a check to add these values on larger screens only.

Support for Butterchurn is still limited, and there is an [open PR](https://github.com/captbaritone/webamp/issues/746) on webamp. Quoting from an older reply on another issue: 

> The visualizer is not included in the Webamp npm package. The integration uses private apis, so it only works on the demo site.
> However, we are working on bringing the Milkdrop visualizer into core, but we’re not yet there. 

With that in mind, I believe that what we can add at the moment is a block option to allow users to enable/disable the Milkdrop panel.
