### ISSUE TITLE
Unable to save the post in WordPress 5.8

### ISSUE THREAD

**Issue by cadic** [10up/retro-winamp-block#88]
### Describe the bug

When WinAmp plugin is active, the post could not be saved in WordPress 5.8 with the error `Publishing failed.`

Also, it's not possible to open any existing post for edit: 

```
There has been a critical error on this website. Please check your site admin email inbox for instructions.
```

Works fine with the current WordPress 6.1.1 and 6.2-RC

### Steps to Reproduce

1. Set up WordPress 5.8
2. Install Retro WinAmp Block 1.2.0
3. Try to create new post

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/288381/224044324-55b9e2c7-6c88-4bf0-8ade-d1a1717d1ac4.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
I'd be fine with bumping the WP minimum to 6.1 as we test compat on WP 6.2 and then set the "tested up to" as 6.2.  @cadic would that suffice here?

**Comment by cadic** [comment]
@jeffpaul sounds good to me. I was helping @barneyjeffries with #87 when discovered this issue. Dropping support for WordPress prior to 6.1 will help a lot :)
